monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-Generic_Realtek_Audio_USB_*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Generic_Realtek_Audio_USB*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.path = "plughw:0,0"
        node.nick = "Realtek Audio USB"
        mute = false
        volume = 1.0
      }
    }
  }
]
